name: Build-Thrift-Libraries
on: [push]
jobs:
  build-java:
    strategy:
      matrix:
        java: [8, 17]
        distribution: ['adopt']
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      GRADLE_VERSION: 6.9.2
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Install dependencies
        run: |
          # https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners
          sudo apt-get update -yq
          sudo apt-get install -y --no-install-recommends \
            automake \
            bison \
            flex \
            libssl-dev \
            libtool \
            make \
            pkg-config \
            wget \
            unzip \
            curl

      - name: Setup gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip -q -O /tmp/gradle-$GRADLE_VERSION-bin.zip
          (echo "8b356fd8702d5ffa2e066ed0be45a023a779bba4dd1a68fd11bc2a6bdc981e8f  /tmp/gradle-$GRADLE_VERSION-bin.zip" | sha256sum -c -)
          unzip -d /tmp /tmp/gradle-$GRADLE_VERSION-bin.zip
          mv /tmp/gradle-$GRADLE_VERSION /usr/local/gradle
          ln -s /usr/local/gradle/bin/gradle /usr/local/bin
          gradle --version
